// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/pong": {
            "get": {
                "description": "Pooooooooong",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ping"
                ],
                "summary": "Piiiiiiinggg",
                "responses": {
                    "200": {
                        "description": "pong",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpUtils.HttpJson"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/pong.Pong"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Gets all the users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "GetUsers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpUtils.HttpJsonList"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/userModel.User"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httpUtils.HttpJson": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "any"
                }
            }
        },
        "httpUtils.HttpJsonList": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "any"
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "total": {
                    "type": "integer",
                    "example": 8
                }
            }
        },
        "pong.Pong": {
            "type": "object",
            "properties": {
                "ping": {
                    "type": "string",
                    "example": "pong"
                }
            }
        },
        "userModel.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "example": "matiaslamela1992@gmail.com"
                },
                "first_name": {
                    "type": "string",
                    "example": "Matias"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "last_name": {
                    "type": "string",
                    "example": "Lamela"
                },
                "password": {
                    "type": "string",
                    "example": "1234"
                },
                "picture": {
                    "type": "string",
                    "example": "https://media.revistagq.com/photos/5ca5fb2aeccc6ac985d559a9/1:1/w_707,h_707,c_limit/rickrolling_3543.png"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "example": "escalera92"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
